[package]
name = "rusty_sudokus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
counter = "0.5.5"
cached = "0.34.0"
ahash = "0.7.6"
rayon = "1.5.3"
